name: helloworld                               # <必选项> 包名称 （符合文件名规范）
description: 简洁直白用一句完成组件介绍          # <必选项>
keywords:                                      # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要 
  - base
  - XML
author:                                        # <可选项> 原作者信息
  name: zhiguo.zzg
license: MIT                                   # <必选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：
                                               #    GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
homepage: https://github.com/yoc-components/helloworld

depends:                                       # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
  - minilibc

build_config:                                  # <可选项> 编译配置项
  include:                                     # <可选项> 编译时，影响编译器的-I 参数
    - include                                  #        include 只能是该软件包下的目录，不能使用外部目录
  cflag: ''                                    # <可选项> C 编译器所需要要的编译参数
  cxxflag: ''                                  # <可选项> CXX 编译器所需要要的编译参数
  asmflag: ''                                  # <可选项> 汇编器所需要要参数
  define:                                      # <可选项> 宏定义, 增加编译器的-D 选项
    - HELLOWORLD                               #   对应编译器参数：  -DHELLOWORD
    - XXX=1                                    #   对应编译器参数：  -DXXX=1

source_file:                                   # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
  - "src/*.c"                                  # 例：组件 src 目录下所有的扩展名为 c 的源代码文件

# 组件安装， 将指定的一个或者多个文件安装到目标文件中。每个安装任务由： dest,与 source 组件， dest是相当路径，通常是相对于YoC SDK 安装目录。source是数组，可以使用通配符。
install:                                       
  - dest: "include/"
    source:
      - include/*.h